#!/usr/bin/env python3
"""Generate a personalized Claude Code skill from a description file or interactive input."""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

TEMPLATE_PATH = Path(__file__).parent.parent / "templates" / "skill-template.md"


def load_template() -> str:
    return TEMPLATE_PATH.read_text(encoding="utf-8")


def get_skill_dir() -> Path:
    home = Path.home()
    skill_dir = home / ".claude" / "skills"
    skill_dir.mkdir(parents=True, exist_ok=True)
    return skill_dir


def fill_template(template: str, data: dict) -> str:
    """Simple template fill — replace {{VARS}} with values."""
    result = template
    for key, value in data.items():
        placeholder = f"{{{{{key.upper()}}}}}"
        if isinstance(value, list):
            value = ", ".join(value)
        result = result.replace(placeholder, str(value))
    return result


def interactive_generate():
    """Interactive Q&A to build a skill."""
    print("\n=== skill-forge ===\n")
    print("Forge your hard-won knowledge into a reusable Claude Code skill.\n")

    data = {}

    # Basic info
    data["SKILL_NAME"] = input("Skill name (kebab-case, e.g. github-push): ").strip()
    data["ONE_LINE_DESCRIPTION"] = input("One-line description: ").strip()

    # Environment
    print("\n--- Environment ---")
    data["OS"] = input("OS (e.g. Windows 11 China): ").strip()
    data["SHELL"] = input("Shell (e.g. Git Bash, PowerShell, zsh): ").strip()
    data["NETWORK"] = input("Network constraints (e.g. GFW, corporate proxy, none): ").strip()
    data["TOOLS"] = input("Key tools used: ").strip()
    data["TAGS"] = input("Tags (comma-separated): ").strip()

    # Triggers
    print("\n--- When to invoke ---")
    triggers = []
    for i in range(3):
        t = input(f"Trigger phrase {i + 1} (or empty to skip): ").strip()
        if t:
            triggers.append(t)
    data["TRIGGER_1"] = triggers[0] if len(triggers) > 0 else ""
    data["TRIGGER_2"] = triggers[1] if len(triggers) > 1 else ""
    data["TRIGGER_3"] = triggers[2] if len(triggers) > 2 else ""

    # Proven approach
    print("\n--- Proven approach (the steps that actually worked) ---")
    for i in range(3):
        print(f"\nStep {i + 1}:")
        data[f"STEP_{i + 1}_TITLE"] = input("  Title: ").strip()
        data[f"STEP_{i + 1}_COMMAND"] = input("  Command: ").strip()
        data[f"STEP_{i + 1}_WHY"] = input("  Why this is needed: ").strip()

    # Pitfalls
    print("\n--- Pitfalls (what you tried that failed) ---")
    data["BAD_APPROACH_1"] = input("Failed approach 1: ").strip()
    data["WHY_FAILS_1"] = input("  Why it failed: ").strip()
    data["BAD_APPROACH_2"] = input("Failed approach 2: ").strip()
    data["WHY_FAILS_2"] = input("  Why it failed: ").strip()

    # Verification
    data["VERIFY_COMMAND"] = input("\nVerification command: ").strip()
    data["ADDITIONAL_NOTES"] = input("\nAdditional notes: ").strip()

    # Generate
    print("\nGenerating skill...")
    template = load_template()
    content = fill_template(template, data)

    # Header comment
    header = (
        f"<!-- Generated by skill-forge on {datetime.now().isoformat()} -->\n"
        f"<!-- Environment: {data['OS']} | {data['SHELL']} | {data['NETWORK']} -->\n\n"
    )

    skill_path = get_skill_dir() / f"{data['SKILL_NAME']}.md"
    skill_path.write_text(header + content, encoding="utf-8")

    print(f"\n✓ Skill saved to: {skill_path}")
    print(f"  Use it with: /{data['SKILL_NAME']}")


def from_json(json_path: str):
    """Generate skill from a JSON description file."""
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    template = load_template()
    content = fill_template(template, data)

    header = (
        f"<!-- Generated by skill-forge on {datetime.now().isoformat()} -->\n"
        f"<!-- Environment: {data.get('OS', '?')} -->\n\n"
    )

    skill_path = get_skill_dir() / f"{data['SKILL_NAME']}.md"
    skill_path.write_text(header + content, encoding="utf-8")

    print(f"Skill saved to: {skill_path}")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        from_json(sys.argv[1])
    else:
        interactive_generate()
